-- 코드를 입력하세요
/*SELECT sum(case when CAR_TYPE="SUV" then DAILY_FEE else 0 end) Div count(CAR_TYPE="SUV") as AVERAGE_FEE
from CAR_RENTAL_COMPANY_CAR
*/

SELECT SUM(DAILY_FEE) Div count(CAR_TYPE) as AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE="SUV"