-- 코드를 입력하세요
SELECT
    PRODUCT_CODE,
    PRICE * COALESCE(s.TOTAL_QTY, 0) AS SALES
FROM PRODUCT p
LEFT JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_QTY
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) s ON p.PRODUCT_ID = s.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;
