SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT a
JOIN PATIENT p
ON p.PT_NO = a.PT_NO
JOIN DOCTOR d
ON d.DR_ID = a.MDDR_ID and d.MCDP_CD = "CS"
WHERE DATE(APNT_YMD) = '2022-04-13'
AND APNT_CNCL_YN='N'
ORDER BY APNT_YMD