-- 코드를 입력하세요
SELECT CATEGORY,sum(SALES) as TOTAL_SALES
FROM BOOK_SALES s
JOIN BOOK b
ON s.BOOK_ID=b.BOOK_ID
WHERE SALES_DATE >= '2022-01-01'
AND SALES_DATE < '2022-02-01'
GROUP BY CATEGORY
ORDER BY CATEGORY 
